### PR TITLE
Some fixes for autoinstallation scripts

### LINKED ISSUE #8: Android build failed
Build failing with this exception:
`* Where:
Script '/Users/catsoft/Desktop/duello/mobile/node_modules/react-native-unimodules/gradle.groovy' line: 102`
`Cannot cast object '[]' with class 'java.util.ArrayList' to class 'java.util.Map' due to: groovy.lang.GroovyRuntimeException: Could not find matching constructor for: java.util.Map()`

### PR DESCRIPTION
**Pull request by tsapeta**
Fixes #8

### CODE REVIEW

File: scripts/postinstall.js [hunk 1]
```diff
@@ -0,0 +1,14 @@
...
+
+const packageJson = require('../package.json');
+
+const RESET = '\x1b[0m';
+const RED   = '\x1b[31m';
+const GREEN = '\x1b[32m';
+const BLUE  = '\x1b[34m';
+
+console.info(`
+${GREEN}Successfully installed ${RED}react-native-unimodules${GREEN}. It contains the core Unimodules infrastructure and a collection of unimodules that are commonly depended on by other unimodules. You'll need to configure your project before using other unimodules like ${RED}expo-camera${GREEN}, ${RED}expo-media-library${GREEN}.
```
Comment (sjchmiela) [inline scripts/postinstall.js]:
```suggestion
${GREEN}Successfully installed ${RED}react-native-unimodules${GREEN}. This package contains core unimodules that are commonly depended on by other unimodules. You will need to configure your project before using other unimodules like ${RED}expo-camera${GREEN}, ${RED}expo-media-library${GREEN}.
```

File: cocoapods.rb [hunk 2]
```diff
@@ -50,31 +50,35 @@ def use_unimodules!(custom_options = {})
...
+      puts brown "Make sure following dependencies of your project are resolving to one specific version:"
+
+      puts ' ' + unimodules_duplicates
+        .uniq
+        .map { |package_name| green(package_name) }
+        .join(', ')
+    end
+  else
+    puts
+    puts brown 'Unimodules not found :('
```
Comment (sjchmiela) [inline cocoapods.rb]:
```suggestion
    puts brown "No unimodules found. Are you sure you've installed JS dependencies before installing pods?"
```

File: gradle.groovy [hunk 3]
```diff
@@ -74,34 +74,39 @@ ext.useUnimodules = { Map customOptions = [] ->
...
-    println ' ' + duplicates
-      .collect { unimoduleName -> Colors.GREEN + unimoduleName + Colors.NORMAL }
-      .join(', ')
+      println ' ' + duplicates
+        .collect { unimoduleName -> Colors.GREEN + unimoduleName + Colors.NORMAL }
+        .join(', ')
+    }
+  } else {
+    println()
+    println Colors.YELLOW + 'Unimodules not found :(' + Colors.NORMAL
```
Comment (sjchmiela) [inline gradle.groovy]:
```suggestion
    println Colors.YELLOW + "No unimodules found. Are you sure you've installed JS dependencies?" + Colors.NORMAL
```

**Comment by sjchmiela** [comment]
Fixes https://github.com/unimodules/react-native-unimodules/issues/8
